#!/usr/bin/perl
use strict;
use warnings;
use File::Basename;
use File::Spec;
use lib File::Spec->catdir(dirname(__FILE__), 'lib');
use twitterutils;

use 5.10.0;

my $nt = twitterutils->init;

while (<>) {
    print "Blocking $_";
    chomp;
    s/\s+.*//;
    use Data::Dumper; warn Dumper($_);
    eval {
        my $user = $nt->create_block(+{ id => $_ });
        warn Dumper($user);
    };
    warn "ERR: $@" if $@;
    sleep 1;
}

